# Target-specific tests
name: CI (by target)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]
  merge_group:

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  check-diff:
    uses: ./.github/workflows/check-diff.yml

  chisel:
    uses: ./.github/workflows/chisel-tests.yml
    needs: check-diff